table_name: Superset Weekly Commits
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: main
sql: 'SELECT datetime(week, ''unixepoch'') as week, total from "https://api.github.com/repos/apache/superset/stats/commit_activity"

  '
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: 7edda5f1-d1e1-457e-b3c5-2b850071eb23
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: total
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: week
  verbose_name: null
  is_dttm: true
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
version: 1.0.0
database_uuid: fe1710ff-33b3-4542-82ec-005a84cd2f50
